### ISSUE TITLE
can't able to get in my drive

### ISSUE THREAD

**Issue by HITLER-KILLER** [maple3142/heroku-aria2c#59]
hey i am not to get able to see files in my drive after downloading and when i always launch the app it always need aria secret and i am not able to do the 3rd point given because i did't understand 

Find the drive you want to use, and copy its type = ... to ... token = ... section.
please reply me as soon as possible

**Comment by maple3142** [comment]
FAQ:
### I don't know how to setup Rclone, can you help me?
No. I thought the instructions above are enough.

**Comment by mangpa444** [comment]
The real problem is rclone config.
You don't need to remove line break and replace it with /n
Directly put it:ex:
_____________________________________________
type = drive (I prefer it ,it allows to do anything thing u want to do with gdrive)
client_id = YOUR WISH
client_secret = YOUR WISH
token = {"access_token":"xyz"}
------__________________________------
RCLONE_DESTINATION : /ur_drive_start_here/ur_drive_folder
