### ISSUE TITLE
Can't Upload to Gdrive

### ISSUE THREAD

**Issue by ashish453** [maple3142/heroku-aria2c#62]
I have copy the config file from my pc rclone.config.
I have also replaced all line brake with \n.
In RCLONE_DESTINATION i have just typed /.
But After Download has finished I can't see the file in my drive.
The files are still in "View Download File"

I think the problem is with RCLONE_DESTINATION.
Suppose I have A folder In my Gdrive names United folder then how to enter its path in RCLONE_DESTINATION.

Note: I am using Heroku Platform to deploy this app.

**Comment by maple3142** [comment]
I don't know

**Comment by mangpa444** [comment]
The real problem is rclone config.
You don't need to remove line break and replace it now.
Directly put only the following in the following order::::
____________________________/_____________&_____
type = drive (I prefer it ,it allows to do anything thing u want to do with gdrive)
client_id = YOUR WISH
client_secret = YOUR WISH
token = {"access_token":"xyz"}
__________________________________________________

RCLONE_DESTINATION : /ur_drive_start_here/ur_drive_folder
